Update repo to support WCSS and tokens MAJOR updates
AlaskaAirlines/auro-checkbox pull request #114
Opened 2023-10-10 03:29 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #113 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

This commit updates to the new major releases of WCSS and auro design tokens. Due to code changes in Auro design tokens, all references to --auro were updated to --ds. Other token ref changes are due to deprecated tokens.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-10-10 15:14 UTC, jason-capsule42 requested changes
Need to run a build here. The api.md file should have a change because of the typos you fixed.

2023-10-10 15:48 UTC, blackfalcon commented
> Need to run a build here. The api.md file should have a change because of the typos you fixed.

Build was updated and committed. FYI... this code is supposed to run the build in the remote and then commit back to the repo. I created a new issue to look into this. 

- https://github.com/AlaskaAirlines/WC-Generator/issues/426

https://github.com/AlaskaAirlines/auro-checkbox/blob/03777edf3c5e93246f40cc6bd32d20e69b8e628f/package.json#L110-L117

2023-10-10 21:18 UTC, blackfalcon commented
This PR is blocked as the dependency on auro icons was reverted 

- https://github.com/AlaskaAirlines/Icons/issues/211

This update will need to be re-applied and a solution shipped for auro-icon shipped as well before this can be completed. 

- https://github.com/AlaskaAirlines/auro-icon/issues/94

2023-12-13 22:27 UTC, Patrick-Daly-AA commented
@blackfalcon , "pick this up again and finish it"

2024-01-09 00:47 UTC, jason-capsule42 requested changes
Local host of this branch doesn't work with tabbing focus to a checkbox but it does work on the docsite.

Localhost API page examples - checkbox is being rendered on the wrong side of the element.

2024-01-09 00:47 UTC, jason-capsule42 commented on src/auro-checkbox.js
> + * @attr {Boolean} disabled - If set to true, the checkbox will be not clickable.
```suggestion
 * @attr {Boolean} disabled - If set to true, the checkbox will not be clickable.
```

2024-01-09 00:47 UTC, jason-capsule42 commented on src/auro-checkbox.scss
> +  --cbxLocation: var(--ds-size-50);
```suggestion
  --cbxLocation: var(--ds-size-50, $ds-size-50);
```

2024-01-09 16:20 UTC, jordanjones243 commented
> Local host of this branch doesn't work with tabbing focus to a checkbox but it does work on the docsite.
> 
> Localhost API page examples - checkbox is being rendered on the wrong side of the element.
> 
> <img alt="Screenshot 2024-01-08 at 7 48 52 PM" width="909" src="https://private-user-images.githubusercontent.com/23223137/295070744-bc526312-c3b2-4b41-94b2-01a27d8ed9ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTc0NTMsIm5iZiI6MTcwNDgxNzE1MywicGF0aCI6Ii8yMzIyMzEzNy8yOTUwNzA3NDQtYmM1MjYzMTItYzNiMi00YjQxLTk0YjItMDFhMjdkOGVkOWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE2MTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MzdkNGVjMzg3MTEzZDU4NWUxZjM5OTkwYmExODJiNDExNWZiMTY1YmE5ODcyM2QxYTE5ZTc0ZWE2MDdjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q26HUU5HnmAxKJOuKdt5KP5_1F1xxb0DRK955izy-Zg">

This issue does not occur on my localhost, we can discuss this further together if this bug still persists for you. All other issues have been addressed.

2024-01-10 21:35 UTC, jason-capsule42 approved these changes

2024-01-10 21:38 UTC, merged

2024-01-10 21:40 UTC, blackfalcon commented
:tada: This PR is included in version 2.0.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-checkbox/v/2.0.4)
- [GitHub release](https://github.com/AlaskaAirlines/auro-checkbox/releases/tag/v2.0.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: