fix(pencil): correct 'engines' property in package.json to align with other Auro projects
AlaskaAirlines/auro-checkbox pull request #61
Opened 2022-06-08 20:56 UTC by MattSidor

# Alaska Airlines Pull Request

Changed the allowed version ranges of node in `"engines"` property of `package.json` to allow versions 12+ to install the project.

**Fixes:** #60 

## Summary:

This aligns with other recently-updated Auro projects that specify the `"engines"` property.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [X] Other (please elaborate)

This affects consumers who wish to `npm install` the library, or contributors who wish to work on it in their local development environment.

## Checklist:

- [X] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

2022-06-08 21:27 UTC, blackfalcon requested changes
Everything looks great, but I am thinking you copied the example commit message from the contrib guidelines? 

Please update the commit to something like the following:

```
fix(package): update 'engines' property to support install with node #60
```

2022-06-08 21:32 UTC, MattSidor commented
You're right, I copied the example; I misunderstood the purpose of what goes in the parentheses. What does "pencil" refer to in that example exactly? For my future PRs, how do I find out what to put in for the scope, or is it subjective? I wouldn't have known to use "package" for this one.

2022-06-09 17:56 UTC, blackfalcon approved these changes

2022-06-09 17:56 UTC, merged

2022-06-09 17:59 UTC, AuroDesignSystem commented
:tada: This PR is included in version 1.1.10 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-checkbox/v/1.1.10)
- [GitHub release](https://github.com/AlaskaAirlines/auro-checkbox/releases/tag/v1.1.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: